UKGovernmentBEIS/desnz-home-energy-retrofit-beta

- HerPublicWebsite/ExternalServices/GoogleAnalytics/GoogleAnalyticsService.cs
- HerPublicWebsite/Views/Shared/_Layout.cshtml
- HerPublicWebsite/appsettings.DEV.json
- HerPublicWebsite/appsettings.Production.json
- HerPublicWebsite/appsettings.json
The new events still need to be called from somewhere, and the GA4 configuration needs to know the urls of pages we haven't done yet so this isn't complete. I'll put the ticket in blocked, but there's no reason not to commit this code now.
> feat: Add google analytics IDs and events

- HerPublicWebsite.BusinessLogic/ExternalServices/S3FileWriter/S3FileWriter.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/S3FileWriter/S3FileWriterConfiguration.cs
- HerPublicWebsite/Startup.cs
- HerPublicWebsite/appsettings.Production.json
- HerPublicWebsite/appsettings.json
We weren't adding the S3 configuration in Startup.cs, and at the same time I thought we may as well make the region configurable - unless we particularly want to hardcode `eu-west-2`?
> chore: Configure S3 config, add make region configurable

- HerPublicWebsite/Models/Questionnaire/ConfirmationViewModel.cs
- HerPublicWebsite/Models/Questionnaire/EligibleViewModel.cs
- HerPublicWebsite/Models/Questionnaire/IneligibleViewModel.cs
- HerPublicWebsite/Models/Questionnaire/NotTakingPartViewModel.cs
- HerPublicWebsite/Views/Questionnaire/Confirmation.cshtml
- HerPublicWebsite/Views/Questionnaire/Eligible.cshtml
- HerPublicWebsite/Views/Questionnaire/Ineligible.cshtml
The `CabinetOffice.GovUkDesignSystem` package here is built from [this branch](https://github.com/UKGovernmentBEIS/govuk-design-system-dotnet/pull/11) which is just the current one but merged with the upstream which adds more attributes to the GovUkTextInput helpers
> BEISHER-648: Added validation to email addresses

- HerPublicWebsite/Views/Questionnaire/Confirmation.cshtml
- HerPublicWebsite/Views/Questionnaire/Ineligible.cshtml
- HerPublicWebsite/Views/Questionnaire/NotTakingPart.cshtml
The alert role causes screenreaders to prioritise the success alert box, so it is focused and read first when the page loads (which is good here as it is just an alert added to the previous page)
> BEISHER-714: Add alert role to success boxes

- HerPublicWebsite/Middleware/SecurityHeadersMiddleware.cs
- HerPublicWebsite/Views/Questionnaire/Confirmation.cshtml
- HerPublicWebsite/Views/Shared/_Layout.cshtml
I've done a bit more investigation into this, and tried to implement a policy based on Google's recommendation: https://csp.withgoogle.com/docs/strict-csp.html
They also provide a tool to evaluate a policy: https://csp-evaluator.withgoogle.com/
We should double-check this matches the pen-test report, but my experience is that these rarely tell you specific configuration to use for your app, and tend to give you general advice like 'avoid unsafe-inline'.
The recommendation doesn't include any restrictions on `style-src`, so Kat's issue will be resolved :)
> feat: Add strict CSP

- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesApi.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesDpaDto.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesLpiDto.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesPostcodeResponseDto.cs
- HerPublicWebsite.UnitTests/BusinessLogic/ExternalServices/OsPlaces/OsPlacesApiTests.cs
- HerPublicWebsite.UnitTests/BusinessLogic/ExternalServices/OsPlaces/OsPlacesLpiDtoTests.cs
See the example that triggered this ticket:
All flats are included and de-duped.
> BH-711: Flat addresses

- HerPublicWebsite/Services/Cookies/CookieService.cs
- HerPublicWebsite/Startup.cs
After completing the questionnaire, all three created cookies have `HttpOnly` and `Secure` set to true, as advised
> BH-769: Make all cookies have safer settings

- HerPublicWebsite.BusinessLogic/Models/Questionnaire.cs
Just a small logic error, since `EpcConfirmedCorrect` is `null` if you never went to the confirmation page
> BEISHER-801: Fixed low EPCs being reported as Unknown

- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesApi.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesLpiDto.cs
- HerPublicWebsite.UnitTests/BusinessLogic/ExternalServices/OsPlaces/OsPlacesApiTests.cs
- HerPublicWebsite.UnitTests/BusinessLogic/ExternalServices/OsPlaces/OsPlacesLpiDtoTests.cs
Filter out address that aren't residential properties. We now use the same criteria as R2V
Specific problem case was buildings containing flats. but this should also remove any other address that isn't a residential property.
> Beisher 808 filter addresses

- HerPublicWebsite/Controllers/StaticPagesController.cs
- HerPublicWebsite/ExternalServices/GoogleAnalytics/GoogleAnalyticsService.cs
- HerPublicWebsite/Views/StaticPages/DigitalAssistance.cshtml
- Added a DigitalAssistance view and method in the StaticPagesController
- Added a new method in the GoogleAnalyticsService to send a digital assistance event, which sets a 'true' flag when a user lands on the digital assistance page
- Changes are not yet testable as we are waiting for GA credentials needed to access the GA site
> BEISHER-826: Add digital assistance view and controller

- HerPublicWebsite/Views/StaticPages/DigitalAssistance.cshtml
We have been told that the desired page title is `HUG2 | Digital Assistance Landing Page | GOV.UK`, however the way that the layout html is structured means that we inject a page title into a title template, so currently our page title would be `Digital Assistance Landing Page | Check if you are eligible for an energy grant for a home with no gas boiler | Gov.uk`.
We could ask if this is OK with the client; however, I think our title template is quite long so we might want to rework that too, e.g. 'Home Upgrade Grant | GOV.UK' . 
For some context, this is the dynamic HTML code snippet from _Layout.cshtml which generates page titles:
`<title>@(ViewBag.Title != null ? ViewBag.Title + " -" : "") @Constants.SERVICE_NAME - Gov.UK</title>`
@AyaPK
> BEISHER-NONE: Add tab title to the digital assistance page

- HerPublicWebsite/Controllers/HealthCheckController.cs
- HerPublicWebsite/Startup.cs
The 500s on internal health checks were coming from the internal check going over HTTP (i.e. no SSL), and our antiforgery cookie having `CookieSecurePolicy.Always` set on it. Was originally going to exclude health-check from antiforgery, but checked SEA (see [here](https://github.com/UKGovernmentBEIS/beis-simple-energy-advice-beta/blob/main/SeaPublicWebsite/Startup.cs#L120)) and saw that it just didn't set these properties on the cookie, so opted for that approach.
> PC-493 Be more lenient with antiforgery cookie to allow health-check to work

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
Updating status of Bournemouth, Christchurch and Poole to Live (matching Dorset, the other council in their consortium, per confirmation from Gareth).
> HER-NONE: Update BCP LA status to Live

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
Note that this PR is to **staging**.
We need to apply this change as a hotfix, so do not want to include recent additions to `develop`, i.e. https://github.com/UKGovernmentBEIS/desnz-home-energy-retrofit-beta/pull/249
> PC-853: Set Croydon's status to "Pending".

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
Reverts UKGovernmentBEIS/desnz-home-energy-retrofit-beta#261
As discussed on [PC-853](https://beisdigital.atlassian.net/browse/PC-853), this change is no longer required.
> Revert "PC-853: Set Croydon's status to "Pending"."

- HerPublicWebsite/Views/Questionnaire/NotParticipating.cshtml
Fixed issue with incorrect redirect from email entry on "Not Participating" page to "Not Taking Part"
> PC-776: UAT bugfix: Incorrect Redirect from Not Participating

- HerPublicWebsite.BusinessLogic/ExternalServices/EmailSending/GovUkNotifyApi.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/EmailSending/GovUkNotifyConfiguration.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/EmailSending/IEmailSender.cs
- HerPublicWebsite.BusinessLogic/Services/RegularJobs/PendingReferralNotificationService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/ExternalServices/EmailSending/GovUkNotifyApiTests.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/PendingReferralNotificationServiceTests.cs
- HerPublicWebsite.UnitTests/Helpers/OptionsHelper.cs
- HerPublicWebsite/Program.cs
- HerPublicWebsite/Startup.cs
- HerPublicWebsite/appsettings.json
- README.md
closes [PC-696](https://beisdigital.atlassian.net/browse/PC-696)
adds a monthly (on the 1st of the month) cronjob to send out a pending referral report email
the ticket did not explicitly specify what class of email this is, so speaking with Glenn we've agreed to call it a "pending referral report"
the template on GOV.UK notify is "Pending Referral Report"
the ticket didn't specifically mention also exactly whom is on the mailing list for these emails; for now I made a new config value `PendingReferralEmailRecipients` where a list can be specified, as I'm not sure if `ComplianceEmailRecipients` is practically the correct list
tests are included for the two service interactions
> PC-696 Set up scheduled monthly email

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityConsortiums.cs
To complete the CPCA onboarding in [PC-888](https://beisdigital.atlassian.net/browse/PC-888), we need to fix up the list of LAs under the CPCA.
The agreed changes are:
* Remove **Basildon Borough Council** from the CPCA
* Add **Oxford City Council** to the CPCA
There was an additional question around whether or not **Tonbridge and Malling Borough Council** should be removed, but it was decided to leave them in for the meantime.
> PC-888: Update CPCA consortium members

- HerPublicWebsite/Views/ReferralRequestFollowUp/ResponsePage.cshtml
Updated copy test on ResponsePage.cshtml to let users know not to answer if the question is not applicable to them
Updated the GovNotify template email to include the caveat copy text.
> PC-995: Add caveat to SLA compliance email that users are sent

- HerPublicWebsite.UnitTests/Website/Services/Cookies/CookieServiceTests.cs
We deliberately don't cover all test cases - they're split across three tests. Hopefully this will save someone a little time in rediscovering this in future!
n/a
> PC-NONE: Add comments to clarify expected test behaviour

- HerPublicWebsite.ManagementShell/FakeReferralGenerator.cs
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1133)
noticed on portal this morning that the referrals generated on dev yesterday were not present
looking into it this would happen as most referrals were already marked as written to csv, even if they weren't
changed this to always be false
this ensures that all fake referrals will be written to the portal the next day
> PC-1133: Fix written to csv property

- HerPublicWebsite.BusinessLogic/Models/Enums/HasGasBoiler.cs
- HerPublicWebsite/Constants.cs
- HerPublicWebsite/Models/Questionnaire/GasBoilerViewModel.cs
- HerPublicWebsite/Views/Questionnaire/CheckAnswers.cshtml
- HerPublicWebsite/Views/Questionnaire/DirectToEco.cshtml
- HerPublicWebsite/Views/Questionnaire/GasBoiler.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1235)
Changed wording to include "mains" before gas boiler
> PC-1235 gas boiler wording change

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1352)
offboards stratford upon avon into our new NoLongerParticipating status
> PC-1352: Offboarding of LAs

- HerPublicWebsite/Views/Questionnaire/NoLongerParticipating.cshtml
- HerPublicWebsite/Views/Questionnaire/NotParticipating.cshtml
- HerPublicWebsite/Views/Questionnaire/NotTakingPart.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1159)
adds a ternary to the Not Participating, No Longer Participating & Not Taking Part pages to show a different message if 'no' is selected
not taking part
not participating
no longer participating
> PC-1159: Unclear contact details flow on LA Not Taking Part page

- HerPublicWebsite/compile-sass-and-js.js
now refers to build output from net8.0
> PC-NONE: bump net version in compile js script

- .github/workflows/build-and-run-tests.yml
see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> PC-NONE: Bump upload-artifacts to v4
