- HerPublicWebsite.BusinessLogic/Models/ReferralRequest.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ReferralRequestTests.cs
I'm not sure about how this will be called as we haven't got that far in the user journey yet, but the basic logic is there.
> feat: Generate referral code

- HerPublicWebsite.BusinessLogic/Models/Enums/QuestionFlowStep.cs
- HerPublicWebsite.BusinessLogic/Models/Questionnaire.cs
- HerPublicWebsite.BusinessLogic/Models/ReferralRequest.cs
- HerPublicWebsite.BusinessLogic/Services/QuestionFlow/QuestionFlowService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/QuestionFlowServiceTests.cs
- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/DirectToEcoViewModel.cs
- HerPublicWebsite/Models/Questionnaire/SelectAddressViewModel.cs
- HerPublicWebsite/Services/QuestionnaireService.cs
- HerPublicWebsite/Views/Questionnaire/DirectToEco.cshtml
- HerPublicWebsite/Views/StaticPages/Index.cshtml
Move the boiler question to the start of the flow and tidy up some other bits
> Beisher 493 move boiler question

- .dockerignore
- Dockerfile
- HerPublicWebsite/HerPublicWebsite.csproj
- HerPublicWebsite/Startup.cs
- HerPublicWebsite/appsettings.json
- HomeEnergyRetrofit.sln
Adds a postgres cache for session storage and a dockerfile
The package I've used for the distributedcache isn't massively popular (https://www.nuget.org/packages/Community.Microsoft.Extensions.Caching.PostgreSql) but it seemed to be the best 'out of the box' result. It's probably not excessively hard to implement our own version if you think it looks a bit ropey.
> Beisher 546 database sessions

- HerPublicWebsite.BusinessLogic/Models/Enums/QuestionFlowStep.cs
- HerPublicWebsite.BusinessLogic/Models/Questionnaire.cs
- HerPublicWebsite.BusinessLogic/Services/QuestionFlow/QuestionFlowService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/QuestionnaireTests.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/QuestionFlowServiceTests.cs
- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/CheckAnswersViewModel.cs
- HerPublicWebsite/Models/Questionnaire/OwnershipStatusViewModel.cs
- HerPublicWebsite/Views/Questionnaire/CheckAnswers.cshtml
- HerPublicWebsite/Views/Questionnaire/SelectLocalAuthority.cshtml
Also fixed issue with validation in OwnershipStatus
> BEISHER-212: Added Check answers page

- HerPublicWebsite/Controllers/HealthCheckController.cs
- HerPublicWebsite/Views/HealthCheck/Index.cshtml
We already have an exception in the basic auth middleware for the `/health-check` route, but didn't actually implement one
> feat: Add health check route

- HerPublicWebsite/Views/Error/ServiceIssue.cshtml
> BEISHER-305: Service issue page

- HerPublicWebsite.BusinessLogic/Models/Enums/QuestionFlowStep.cs
- HerPublicWebsite.BusinessLogic/Models/Questionnaire.cs
- HerPublicWebsite.BusinessLogic/Services/QuestionFlow/QuestionFlowService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/QuestionFlowServiceTests.cs
- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/NotTakingPartViewModel.cs
- HerPublicWebsite/Views/Questionnaire/NotTakingPart.cshtml
> BEISHER-557: Local authority not taking part

- HerPublicWebsite.BusinessLogic/Models/Enums/QuestionFlowStep.cs
- HerPublicWebsite.BusinessLogic/Services/QuestionFlow/QuestionFlowService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/QuestionFlowServiceTests.cs
- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/IneligibleWalesViewModel.cs
- HerPublicWebsite/Views/Questionnaire/IneligibleWales.cshtml
> Specific service unsuitable page for Wales

- HerPublicWebsite.BusinessLogic/Models/Enums/QuestionFlowStep.cs
- HerPublicWebsite.BusinessLogic/Services/QuestionFlow/QuestionFlowService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/QuestionFlowServiceTests.cs
- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/IneligibleScotlandViewModel.cs
- HerPublicWebsite/Views/Questionnaire/IneligibleScotland.cshtml
> BH-600: Specific service unsuitable page for Scotland

- HerPublicWebsite.BusinessLogic/Models/Enums/QuestionFlowStep.cs
- HerPublicWebsite.BusinessLogic/Services/QuestionFlow/QuestionFlowService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/QuestionFlowServiceTests.cs
- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/IneligibleNorthernIrelandViewModel.cs
- HerPublicWebsite/Views/Questionnaire/IneligibleNorthernIreland.cshtml
> BH-605: Specific service unsuitable page for Northern Ireland

- HerPublicWebsite/Views/Questionnaire/SelectLocalAuthority.cshtml
> BEISHER-611: Tweaked styling of select local authority page

- HerPublicWebsite/Views/StaticPages/Index.cshtml
> BEISHER-606: Made a few more tweaks to start page

- HerPublicWebsite/Views/StaticPages/Index.cshtml
A minor colectomy had to occur
> BEISHER-606: Removed a colon (Last tweak hopefullly)

- HerPublicWebsite/Views/StaticPages/Index.cshtml
> feat: Add phone details to start page

- HerPublicWebsite/Helpers/CustomPhoneAttribute.cs
- HerPublicWebsite/Helpers/ValidUkPhoneNumberAttribute.cs
- HerPublicWebsite/HerPublicWebsite.csproj
- HerPublicWebsite/Models/Questionnaire/EligibleViewModel.cs
At the top of the page:
On the input:
> BH-644: Add phone number validation

- HerPublicWebsite/Views/Questionnaire/CheckAnswers.cshtml
I've checked it with NVDA in Chrome and it seems to be read out as intended :)
> BEISHER-684: Added visually hidden text for action links on check answers page)

- HerPublicWebsite/Views/Questionnaire/Eligible.cshtml
> BEISHER-722: Tweak wording on eligible page

- HerPublicWebsite/Views/StaticPages/PrivacyPolicy.cshtml
Should match the text in Appendix E here: https://beisgov.sharepoint.com/:w:/r/sites/HUG/_layouts/15/Doc.aspx?sourcedoc=%7B20d2b9ba-1326-4e6e-ad83-893d94cb4672%7D&action=edit&wdPid=36eae536&cid=eb6383e6-80f4-4f5b-82e0-3400d23ddd1b
> feat: Add privacy policy content

- HerPublicWebsite/Views/Questionnaire/Ineligible.cshtml
> BEISHER-753: Changed wording on ineligible page

- HerPublicWebsite/Views/Questionnaire/Eligible.cshtml
> BEISHER-738: Changed wording on eligible, but not yet onboard page

- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/SelectLocalAuthorityViewModel.cs
- HerPublicWebsite/Views/Questionnaire/SelectLocalAuthority.cshtml
- HerPublicWebsite/wwwroot/css/_her-custom.scss
> BH-709: Allow searching for local authorities

- HerPublicWebsite/Views/Questionnaire/Address.cshtml
- HerPublicWebsite/Views/Questionnaire/ManualAddress.cshtml
> BEISHER-732: Replace text input placeholders with hint text

- HerPublicWebsite/Views/Questionnaire/Confirmation.cshtml
> BEISHER-739: Moved email confirmation text below "What happens next" on confirmation page

- HerPublicWebsite/Views/Questionnaire/SelectAddress.cshtml
> BEISHER-734: Moved "Address not listed" link above Continue button

- HerPublicWebsite/Views/Questionnaire/Eligible.cshtml
> BEISHER-774: Moved "I don't want to share my information" link above Submit button

- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/ExternalServices/GoogleAnalytics/GoogleAnalyticsService.cs
Add a GA event to the start of the journey. If the user doesn't accept cookies this still triggers but anonymously.
> Beisher 813 journey start event

- HerPublicWebsite.BusinessLogic/ExternalServices/S3FileWriter/S3Configuration.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/S3FileWriter/S3FileWriter.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/S3FileWriter/S3FileWriterConfiguration.cs
- HerPublicWebsite/Startup.cs
- HerPublicWebsite/appsettings.Development.json
- HerPublicWebsite/appsettings.json
- README.md
Tested by writing files from the public site, then reading them from the portal site
> feat: Add local S3 bucket

- HerPublicWebsite/Views/Questionnaire/Ineligible.cshtml
The income rules are quite complicated, so if someone is only disqualified by income we suggest that they talk to their LA to see if they can still qualify under the more complicated rules
> Change text on ineligible

- HerPublicWebsite/Views/Error/ServiceIssue.cshtml
> feat: Update error page text

- HerPublicWebsite/Constants.cs
- HerPublicWebsite/Views/StaticPages/AccessibilityStatement.cshtml
Making the accessibility feedback form the same is deliberate
> Update feedback link

- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/LaMapping.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesApi.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesDpaDto.cs
- HerPublicWebsite.BusinessLogic/ExternalServices/OsPlaces/OsPlacesLpiDto.cs
- HerPublicWebsite.UnitTests/BusinessLogic/ExternalServices/OsPlaces/OsPlacesApiTests.cs
- HerPublicWebsite.UnitTests/BusinessLogic/ExternalServices/OsPlaces/OsPlacesLpiDtoTests.cs
- HerPublicWebsite/Views/Questionnaire/Address.cshtml
Also fix LPI data to use the custodian code mapping
> Improve address filtering

- HerPublicWebsite/Controllers/StaticPagesController.cs
Change where / redirects to in line with SEA implementation
> BEISHER-425: Redirect / to the HUG2 GDS start page

- HerPublicWebsite/Controllers/StaticPagesController.cs
> BEISHER-NONE: Change digital assistance URL by removing hyphen

- HerPublicWebsite/Startup.cs
- HerPublicWebsite/robots.txt
Added robots.txt file to the HerPublicWebsite project root (hopefully this is the correct place)
Added robots.txt configuration to the Configure method in Startup.cs
> BEISHER-NONE: Add robots.txt file and config to Startup.cs

- HerPublicWebsite/robots.txt
Testing with https://technicalseo.com/tools/robots-txt/
> BEISHER-NONE: Amend robots.txt file

- HerPublicWebsite/Startup.cs
- HerPublicWebsite/Views/StaticPages/DigitalAssistance.cshtml
New page title for DA landing page:
Digital Assistance Landing Page | Check if you are eligible for an energy grant for a home with no gas boiler | Gov.uk
> Merge develop into staging

- HerPublicWebsite.BusinessLogic/Models/Enums/QuestionFlowStep.cs
- HerPublicWebsite.BusinessLogic/Services/QuestionFlow/QuestionFlowService.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Services/QuestionFlowServiceTests.cs
- HerPublicWebsite/Controllers/QuestionnaireController.cs
- HerPublicWebsite/Models/Questionnaire/PendingViewModel.cs
- HerPublicWebsite/Views/Questionnaire/Eligible.cshtml
- HerPublicWebsite/Views/Questionnaire/Pending.cshtml
https://beisdigital.atlassian.net/browse/PC-529
> Pc 529 pending screen

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
https://beisdigital.atlassian.net/browse/PC-594
> PC-594: Onboarding Tonbridge

- HerPublicWebsite/Views/ReferralRequestFollowUp/ResponsePage.cshtml
Update copy on ReferralFollowUp ResponsePage to match request from the team.
> Update copy on referral follow up response page

- HerPublicWebsite.UnitTests/BusinessLogic/Models/LocalAuthorityDataTests.cs
Additional test to ensure LA data is always documented independently.
> PC-851: LA data test

- HerPublicWebsite/Program.cs
To be reverted after testing in UAT.
> [UAT ONLY] PC-883: Edit email schedule for UAT

- HerPublicWebsite/Program.cs
Reverts UKGovernmentBEIS/desnz-home-energy-retrofit-beta#283
> Revert "[UAT ONLY] PC-883: Edit email schedule for UAT (to be reverted)"

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityConsortiums.cs
> PC-928: Remove Central Bedfordshire from CPCA

- HerPublicWebsite/Program.cs
Reverts UKGovernmentBEIS/desnz-home-energy-retrofit-beta#298
> Revert "PC-944: set up referral emails to send every minute"

- HerPublicWebsite.BusinessLogic/ExternalServices/EmailSending/GovUkNotifyApi.cs
- HerPublicWebsite/Program.cs
for QA on [PC-967](https://beisdigital.atlassian.net/browse/PC-967)
to allow for dev testing, the email will be sent to me & sent on the hour
> PC-967: send compliance email on the hour and hardcode the recipient to me

- HerPublicWebsite.BusinessLogic/ExternalServices/EmailSending/GovUkNotifyApi.cs
- HerPublicWebsite/Program.cs
for QA on [PC-967](https://beisdigital.atlassian.net/browse/PC-967)
reverts the changes made in https://github.com/UKGovernmentBEIS/desnz-home-energy-retrofit-beta/pull/306
> PC-967: revert send compliance email on the hour and hardcode the recipient to me

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
as part of [PC-1022](https://beisdigital.atlassian.net/browse/PC-1022)
changes City of York from Pending to Active
> PC-1022: LA Onboarding

- HerPublicWebsite.BusinessLogic/ExternalServices/EmailSending/GovUkNotifyApi.cs
- HerPublicWebsite/Program.cs
for QA as part of [PC-1022](https://beisdigital.atlassian.net/browse/PC-1022) & [PC-975](https://beisdigital.atlassian.net/browse/PC-975)
increase email frequency and change recipient to me
> PC-1022: make emails frequent

- HerPublicWebsite.BusinessLogic/ExternalServices/EmailSending/GovUkNotifyApi.cs
- HerPublicWebsite/Program.cs
for QA as part of [PC-1022](https://beisdigital.atlassian.net/browse/PC-1022) & [PC-975](https://beisdigital.atlassian.net/browse/PC-975)
restore email frequency & recipients to normal
> PC-1022: undo make emails frequent

- .github/pull_request_template.md
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1081)
this adds a pull request template, with additional check boxes for making sure LA / consortium changes are also made to portal
since this is not yet on main, I copied the template in manually to check it all looks fine
> PC-1081: Add PR template

- .github/pull_request_template.md
- Dockerfile
- HerPublicWebsite.BusinessLogic/Models/ReferralRequest.cs
- HerPublicWebsite.ManagementShell/CommandHandler.cs
- HerPublicWebsite.ManagementShell/DatabaseOperation.cs
- HerPublicWebsite.ManagementShell/FakeReferralGenerator.cs
- HerPublicWebsite.ManagementShell/HerPublicWebsite.ManagementShell.csproj
- HerPublicWebsite.ManagementShell/OutputProvider.cs
- HerPublicWebsite.ManagementShell/Program.cs
- HomeEnergyRetrofit.sln
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1133)
uses the [Bogus](https://github.com/bchavez/Bogus) library to generate fake referrals
these referrals are added directly to the database
adds a new module to the project to add a CLI
docker setup has also been edited to account for this in the build
- do we want tests for this?
> PC-1133 Data on dev/staging environments is not realistic

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1310)
Updated Solihull Borough Council to Live
> PC-1310: LA Onboarding

- .github/pull_request_template.md
now uses the boards in the DESNZ team
> PC-NONE: update miro links in pr template

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1370)
Onboarding Worcestershire county council
> PC-1370: LA Onboarding

- .github/pull_request_template.md
see https://softwiretech.atlassian.net/wiki/spaces/Support/pages/21284519953/DESNZ+GBIS+Help+to+Heat+Flow+Miro+Boards
> PC-NONE: update flow miro link

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
﻿
onboard 3710 nuneaton and bedworth
> PC-1393: LA Onboarding

- HerPublicWebsite.BusinessLogic/Models/LocalAuthorityData.cs
- HerPublicWebsite.UnitTests/BusinessLogic/Models/ExpectedLocalAuthorityData/LocalAuthorityStatuses.cs
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1492)
Erewash  -> Pending to Live
> PC-1492: Change selected LA status to Live

- HerPublicWebsite/Program.cs
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1757)
As agreed by DESNZ, this should be turned off
> PC-1757: Remove Referral Follow Up Notifications job
